const sampleListings = [
  {
    title: "AI Hackathon",
    category: "Tech",
    date: "2026-02-01",
    mode: "Offline",
    location: "Tech Block",
    prize: "₹1,00,000",
    teamSize: "2-4",
    theme: "Artificial Intelligence",
    status: "Open",
    image: "/images/whatsapp-001.jpeg"
  },
  {
    title: "Web Dev Sprint",
    category: "Tech",
    date: "2026-02-03",
    mode: "Online",
    location: "Zoom",
    prize: "₹50,000",
    teamSize: "1-3",
    theme : "Web Development",
    status: "Upcoming",
    image: "/images/whatsapp-002.jpeg"
  },
  {
    title: "Cyber Security CTF",
    category: "Tech",
    date: "2026-02-05",
    mode: "Online",
    location: "CTF Arena",
    prize: "₹75,000",
    teamSize: "2-5",
    theme: "Cybersecurity",
    status: "Open",
    image: "/images/whatsapp-003.jpeg"
  },
  {
    title: "Blockchain Buildathon",
    category: "Tech",
    date: "2026-02-07",
    mode: "Hybrid",
    location: "Innovation Lab",
    prize: "₹1,20,000",
    teamSize: "2-4",
    theme: "Blockchain",
    status: "Upcoming",
    image: "/images/whatsapp-004.jpeg"
  },
  {
    title: "Cloud Computing Jam",
    category: "Tech",
    date: "2026-02-09",
    mode: "Offline",
    location: "Server Room",
    prize: "₹60,000",
    teamSize: "2-3",
    theme: "Cloud",
    status: "Open",
    image   : "/images/whatsapp-005.jpeg"
  },

  {
    title: "IoT Hack Day",
    category: "Tech",
    date: "2026-02-11",
    mode: "Hybrid",
    location: "IoT Lab",
    prize : "₹90,000",
    teamSize: "2-4",
    theme: "Internet of Things",
    status: "Open",
    image: "/images/whatsapp-006.jpeg"
  },
  {
    title: "Data Science Marathon",
    category: "Tech",
    date: "2026-02-13",
    mode: "Online",
    location: "Kaggle",
    prize: "₹1,10,000",
    teamSize: "1-3",
    theme: "Data Science",
    status: "Upcoming",
    image  : "/images/whatsapp-007.jpeg"
  },
  {
    title: "DevOps Challenge",
    category: "Tech",
    date: "2026-02-15",
    mode: "Online",
    location: "GitHub",
    prize: "₹80,000",
    teamSize: "2-5",
    theme: "DevOps",
    status: "Open",
    image: "/images/whatsapp-008.jpeg"
  },
  {
    title: "AR/VR Hack",
    category: "Tech",
    date: "2026-02-17",
    mode: "Offline",
    location: "XR Lab",
    prize: "₹1,40,000",
    teamSize: "2-4",
    theme: "AR VR",
    status: "Upcoming",
    image: "/images/whatsapp-009.jpeg"
  },
  {
    title: "Mobile App Hackathon",
    category: "Tech",
    date: "2026-02-19",
    mode: "Hybrid",
    location: "App Lab",
    prize: "₹70,000",
    teamSize: "1-4",
    theme: "Android iOS",
    status: "Open",
    image: "/images/whatsapp-010.jpeg"
  },

  {
    title: "Quantum Coding Jam",
    category: "Tech",
    date: "2026-02-21",
    mode: "Online",
    location: "Research Portal",
    prize: "₹2,00,000",
    teamSize: "2-3",
    theme: "Quantum Computing",
    status: "Upcoming",
    image: "/images/whatsapp-011.jpeg"
  },
  {
    title: "Startup Hack",
    category: "Tech",
    date: "2026-02-23",
    mode: "Offline",
    location: "Incubation Center",
    prize: "₹1,50,000",
    teamSize: "2-5",
    theme: "Entrepreneurship",
    status: "Open",
    image: "/images/whatsapp-012.jpeg"
  },
  {
    title: "Open Source Sprint",
    category: "Tech",
    date: "2026-02-25",
    mode: "Online",
    location: "GitLab",
    prize: "₹40,000",
    teamSize: "1-4",
    theme: "Open Source",
    status: "Upcoming",
    image: "/images/whatsapp-013.jpeg"
  },
  {
    title: "Game Dev Jam",
    category: "Tech",
    date: "2026-02-27",
    mode: "Offline",
    location: "Game Studio",
    prize: "₹60,000",
    teamSize: "2-4",
    theme: "Game Development",
    status: "Open",
    image: "/images/whatsapp-014.jpeg"
  },
  {
    title: "AI Ethics Hack",
    category: "Tech",
    date: "2026-03-01",
    mode: "Online",
    location: "Meet",
    prize: "₹55,000",
    teamSize: "2-3",
    theme: "AI Ethics",
    status: "Upcoming",
    image: "/images/whatsapp-015.jpeg"
  },

  {
    title: "Robotics Buildathon",
    category: "Tech",
    date: "2026-03-03",
    mode: "Offline",
    location: "Robotics Lab",
    prize: "₹1,30,000",
    teamSize: "2-5",
    theme: "Robotics",
    status: "Open",
    image: "/images/whatsapp-016.jpeg"
  },
  {
    title: "FinTech Hack",
    category: "Tech",
    date: "2026-03-05",
    mode: "Hybrid",
    location: "Finance Lab",
    prize: "₹1,00,000",
    teamSize: "2-4",
    theme: "FinTech",
    status: "Upcoming",
    image: "/images/whatsapp-017.jpeg"
  },
  {
    title: "HealthTech Hack",
    category: "Tech",
    date: "2026-03-07",
    mode: "Online",
    location: "Webex",
    prize: "₹90,000",
    teamSize: "1-3",
    theme: "HealthTech",
    status: "Open",
    image: "/images/whatsapp-018.jpeg"
  },
  {
    title: "EdTech Build",
    category: "Tech",
    date: "2026-03-09",
    mode: "Hybrid",
    location: "Smart Class",
    prize: "₹70,000",
    teamSize: "2-4",
    theme: "EdTech",
    status: "Upcoming",
    image: "/images/whatsapp-019.jpeg"
  },
  {
    title: "AI Research Sprint",
    category: "Tech",
    date: "2026-03-11",
    mode: "Offline",
    location: "Research Center",
    prize: "₹1,80,000",
    teamSize: "2-3",
    theme: "AI Research",
    status: "Open",
    image: "/images/whatsapp-020.jpeg"
  },

  {
    title: "System Design Hack",
    category: "Tech",
    date: "2026-03-13",
    mode: "Online",
    location: "Teams",
    prize: "₹65,000",
    teamSize: "1-3",
    theme: "System Design",
    status: "Upcoming",
    image: "/images/whatsapp-021.jpeg"
  },
  {
    title: "Low Code Hack",
    category: "Tech",
    date: "2026-03-15",
    mode: "Hybrid",
    location: "NoCode Lab",
    prize: "₹50,000",
    teamSize: "2-4",
    theme: "No Code",
    status: "Open",
    image: "/images/whatsapp-022.jpeg"
  },
  {
    title: "Security Automation Hack",
    category: "Tech",
    date: "2026-03-17",
    mode: "Online",
    location: "Security Hub",
    prize: "₹85,000",
    teamSize: "2-5",
    theme: "Automation",
    status: "Upcoming",
    image: "/images/whatsapp-023.jpeg"
  },
  {
    title: "ML Ops Challenge",
    category: "Tech",
    date: "2026-03-19",
    mode: "Hybrid",
    location: "Cloud Lab",
    prize: "₹1,10,000",
    teamSize: "2-4",
    theme: "MLOps",
    status: "Open",
    image: "/images/whatsapp-024.jpeg"
  },
  {
    title: "Metaverse Hack",
    category: "Tech",
    date: "2026-03-21",
    mode: "Online",
    location: "VR World",
    prize: "₹1,60,000",
    teamSize: "2-5",
    theme: "Metaverse",
    status: "Upcoming",
    image: "/images/whatsapp-025.jpeg"
  },
  {
    title: "Inter-College Cricket Tournament",
    category: "Sports",
    date: "2026-02-02",
    mode: "Offline",
    location: "Main Ground",
    prize: "Trophy + ₹50,000",
    teamSize: "11 Players",
    theme: "Cricket",
    status: "Upcoming",
    image: "/images/whatsapp-026.jpeg"
  },
  {
    title: "Football League",
    category: "Sports",
    date: "2026-02-04",
    mode: "Offline",
    location: "Sports Complex",
    prize: "₹40,000",
    teamSize: "7 Players",
    theme: "Football",
    status: "Open",
    image: "/images/whatsapp-027.jpeg"
  },
  {
    title: "Badminton Championship",
    category: "Sports",
    date: "2026-02-06",
    mode: "Offline",
    location: "Indoor Court",
    prize: "₹25,000",
    teamSize: "Singles/Doubles",
    theme: "Badminton",
    status: "Open",
    image: "/images/whatsapp-028.jpeg"
  },
  {
    title: "Basketball Knockout",
    category: "Sports",
    date: "2026-02-08",
    mode: "Offline",
    location: "Court A",
    prize: "₹35,000",
    teamSize: "5 Players",
    theme: "Basketball",
    status: "Upcoming",
    image: "/images/whatsapp-029.jpeg"
  },
  {
    title: "Volleyball Cup",
    category: "Sports",
    date: "2026-02-10",
    mode: "Offline",
    location: "Court B",
    prize: "₹30,000",
    teamSize: "6 Players",
    theme: "Volleyball",
    status: "Open",
    image: "/images/whatsapp-030.jpeg"
  },

  {
    title: "Table Tennis Open",
    category: "Sports",
    date: "2026-02-12",
    mode: "Offline",
    location: "TT Hall",
    prize: "₹20,000",
    teamSize: "Singles",
    theme: "Table Tennis",
    status: "Open",
    image: "/images/whatsapp-031.jpeg"
  },
  {
    title: "Chess Blitz",
    category: "Sports",
    date: "2026-02-14",
    mode: "Online",
    location: "Chess.com",
    prize: "₹15,000",
    teamSize: "Individual",
    theme: "Chess",
    status: "Upcoming",
    image: "/images/whatsapp-032.jpeg"
  },
  {
    title: "Athletics Meet",
    category: "Sports",
    date: "2026-02-16",
    mode: "Offline",
    location: "Track Field",
    prize: "₹45,000",
    teamSize: "Individual",
    theme: "Running",
    status: "Open",
    image: "/images/whatsapp-033.jpeg"
  },
  {
    title: "Kabaddi League",
    category: "Sports",
    date: "2026-02-18",
    mode: "Offline",
    location: "Open Arena",
    prize: "₹55,000",
    teamSize: "7 Players",
    theme: "Kabaddi",
    status: "Upcoming",
    image: "/images/whatsapp-001.jpeg"
  },
  {
    title: "Hockey Tournament",
    category: "Sports",
    date: "2026-02-20",
    mode: "Offline",
    location: "Hockey Ground",
    prize: "₹60,000",
    teamSize: "11 Players",
    theme: "Hockey",
    status: "Open",
    image: "/images/whatsapp-002.jpeg"
  },

  {
    title: "Futsal Cup",
    category: "Sports",
    date: "2026-02-22",
    mode: "Offline",
    location: "Mini Stadium",
    prize: "₹25,000",
    teamSize: "5 Players",
    theme: "Futsal",
    status: "Open",
    image: "/images/whatsapp-003.jpeg"
  },
  {
    title: "Swimming Gala",
    category: "Sports",
    date: "2026-02-24",
    mode: "Offline",
    location: "Aquatic Center",
    prize: "₹35,000",
    teamSize: "Individual",
    theme: "Swimming",
    status: "Upcoming",
    image: "/images/whatsapp-004.jpeg"
  },
  {
    title: "Marathon Run",
    category: "Sports",
    date: "2026-02-26",
    mode: "Offline",
    location: "City Road",
    prize: "Medals + ₹20,000",
    teamSize: "Individual",
    theme: "Marathon",
    status: "Open",
    image: "/images/whatsapp-005.jpeg"
  },
  {
    title: "Carrom Championship",
    category: "Sports",
    date: "2026-02-28",
    mode: "Offline",
    location: "Indoor Hall",
    prize: "₹10,000",
    teamSize: "Singles/Doubles",
    theme: "Carrom",
    status: "Open",
    image: "/images/whatsapp-006.jpeg"
  },
  {
    title: "Wrestling Meet",
    category: "Sports",
    date: "2026-03-02",
    mode: "Offline",
    location: "Gym Arena",
    prize: "₹40,000",
    teamSize: "Individual",
    theme: "Wrestling",
    status: "Upcoming",
    image: "/images/whatsapp-007.jpeg"
  },

  {
    title: "Powerlifting Contest",
    category: "Sports",
    date: "2026-03-04",
    mode: "Offline",
    location: "Fitness Center",
    prize: "₹30,000",
    teamSize: "Individual",
    theme: "Powerlifting",
    status: "Open",
    image: "/images/whatsapp-008.jpeg"
  },
  {
    title: "Yoga Championship",
    category: "Sports",
    date: "2026-03-06",
    mode: "Offline",
    location: "Yoga Hall",
    prize: "₹20,000",
    teamSize: "Individual",
    theme: "Yoga",
    status: "Upcoming",
    image: "/images/whatsapp-009.jpeg"
  },
  {
    title: "Cycling Race",
    category: "Sports",
    date: "2026-03-08",
    mode: "Offline",
    location: "Ring Road",
    prize: "₹25,000",
    teamSize: "Individual",
    theme: "Cycling",
    status: "Open",
    image: "/images/whatsapp-010.jpeg"
  },
  {
    title: "Skating Showdown",
    category: "Sports",
    date: "2026-03-10",
    mode: "Offline",
    location: "Skate Park",
    prize: "₹15,000",
    teamSize: "Individual",
    theme: "Skating",
    status: "Upcoming",
    image: "/images/whatsapp-011.jpeg"
  },
  {
    title: "Kho-Kho League",
    category: "Sports",
    date: "2026-03-12",
    mode: "Offline",
    location: "Play Ground",
    prize: "₹18,000",
    teamSize: "9 Players",
    theme: "Kho-Kho",
    status: "Open",
    image: "/images/whatsapp-012.jpeg"
  },

  {
    title: "Throwball Cup",
    category: "Sports",
    date: "2026-03-14",
    mode: "Offline",
    location: "Court C",
    prize: "₹22,000",
    teamSize: "7 Players",
    theme: "Throwball",
    status: "Upcoming",
    image: "/images/whatsapp-013.jpeg"
  },
  {
    title: "Handball Tournament",
    category: "Sports",
    date: "2026-03-16",
    mode: "Offline",
    location: "Handball Court",
    prize: "₹28,000",
    teamSize: "7 Players",
    theme: "Handball",
    status: "Open",
    image: "/images/whatsapp-014.jpeg"
  },
  {
    title: "Rowing Challenge",
    category: "Sports",
    date: "2026-03-18",
    mode: "Offline",
    location: "Lake Side",
    prize: "₹35,000",
    teamSize: "4 Players",
    theme: "Rowing",
    status: "Upcoming",
    image: "/images/whatsapp-015.jpeg"
  },
  {
    title: "Boxing Championship",
    category: "Sports",
    date: "2026-03-20",
    mode: "Offline",
    location: "Boxing Ring",
    prize: "₹50,000",
    teamSize: "Individual",
    theme: "Boxing",
    status: "Open",
    image: "/images/whatsapp-016.jpeg"
  },
  {
    title: "Archery Contest",
    category: "Sports",
    date: "2026-03-22",
    mode: "Offline",
    location: "Archery Range",
    prize: "₹18,000",
    teamSize: "Individual",
    theme: "Archery",
    status: "Upcoming",
    image: "/images/whatsapp-017.jpeg"
  },
  {
    title: "Dance Fiesta",
    category: "Cultural",
    date: "2026-02-03",
    mode: "Offline",
    location: "Auditorium",
    prize: "₹30,000",
    teamSize: "Solo/Group",
    theme: "Dance",
    status: "Open",
    image: "/images/whatsapp-018.jpeg"
  },
  {
    title: "Battle of Bands",
    category: "Cultural",
    date: "2026-02-05",
    mode: "Offline",
    location: "Open Stage",
    prize: "₹40,000",
    teamSize: "4-8 Members",
    theme: "Music",
    status: "Upcoming",
    image: "/images/whatsapp-019.jpeg"
  },
  {
    title: "Drama Night",
    category: "Cultural",
    date: "2026-02-07",
    mode: "Offline",
    location: "Theatre Hall",
    prize: "₹25,000",
    teamSize: "5-12 Members",
    theme: "Theatre",
    status: "Open",
    image: "/images/whatsapp-020.jpeg"
  },
  {
    title: "Poetry Slam",
    category: "Cultural",
    date: "2026-02-09",
    mode: "Offline",
    location: "Seminar Hall",
    prize: "₹10,000",
    teamSize: "Individual",
    theme: "Poetry",
    status: "Open",
    image: "/images/whatsapp-021.jpeg"
  },
  {
    title: "Fashion Show",
    category: "Cultural",
    date: "2026-02-11",
    mode: "Offline",
    location: "Main Stage",
    prize: "₹35,000",
    teamSize: "6-10 Members",
    theme: "Fashion",
    status: "Upcoming",
    image: "/images/whatsapp-022.jpeg"
  },

  {
    title: "Stand-Up Comedy Night",
    category: "Cultural",
    date: "2026-02-13",
    mode: "Offline",
    location: "Open Air Theatre",
    prize: "₹15,000",
    teamSize: "Individual",
    theme: "Comedy",
    status: "Open",
    image: "/images/whatsapp-023.jpeg"
  },
  {
    title: "Photography Contest",
    category: "Cultural",
    date: "2026-02-15",
    mode: "Online",
    location: "Instagram",
    prize: "₹12,000",
    teamSize: "Individual",
    theme: "Photography",
    status: "Upcoming",
    image: "/images/whatsapp-024.jpeg"
  },
  {
    title: "Short Film Festival",
    category: "Cultural",
    date: "2026-02-17",
    mode: "Offline",
    location: "Mini Theatre",
    prize: "₹28,000",
    teamSize: "2-6 Members",
    theme: "Film Making",
    status: "Open",
    image: "/images/whatsapp-025.jpeg"
  },
  {
    title: "Street Play Competition",
    category: "Cultural",
    date: "2026-02-19",
    mode: "Offline",
    location: "Campus Circle",
    prize: "₹20,000",
    teamSize: "6-12 Members",
    theme: "Nukkad Natak",
    status: "Upcoming",
    image: "/images/whatsapp-026.jpeg"
  },
  {
    title: "Art & Painting Expo",
    category: "Cultural",
    date: "2026-02-21",
    mode: "Offline",
    location: "Art Gallery",
    prize: "₹18,000",
    teamSize: "Individual",
    theme: "Fine Arts",
    status: "Open",
    image: "/images/whatsapp-027.jpeg"
  },

  {
    title: "Classical Music Evening",
    category: "Cultural",
    date: "2026-02-23",
    mode: "Offline",
    location: "Music Hall",
    prize: "₹22,000",
    teamSize: "Solo/Duet",
    theme: "Classical Music",
    status: "Upcoming",
    image: "/images/whatsapp-028.jpeg"
  },
  {
    title: "Rangoli Competition",
    category: "Cultural",
    date: "2026-02-25",
    mode: "Offline",
    location: "Hostel Lawn",
    prize: "₹8,000",
    teamSize: "2-4 Members",
    theme: "Rangoli Art",
    status: "Open",
    image: "/images/whatsapp-029.jpeg"
  },
  {
    title: "Folk Dance Festival",
    category: "Cultural",
    date: "2026-02-27",
    mode: "Offline",
    location: "Cultural Ground",
    prize: "₹30,000",
    teamSize: "6-12 Members",
    theme: "Folk Dance",
    status: "Upcoming",
    image: "/images/whatsapp-030.jpeg"
  },
  {
    title: "Open Mic Night",
    category: "Cultural",
    date: "2026-03-01",
    mode: "Offline",
    location: "Café Arena",
    prize: "₹10,000",
    teamSize: "Individual",
    theme: "Open Mic",
    status: "Open",
    image: "/images/whatsapp-031.jpeg"
  },
  {
    title: "Mehendi Art Contest",
    category: "Cultural",
    date: "2026-03-03",
    mode: "Offline",
    location: "Girls Hostel",
    prize: "₹7,000",
    teamSize: "Individual",
    theme: "Mehendi",
    status: "Upcoming",
    image: "/images/whatsapp-032.jpeg"
  },

  {
    title: "Cultural Quiz",
    category: "Cultural",
    date: "2026-03-05",
    mode: "Online",
    location: "Google Meet",
    prize: "₹12,000",
    teamSize: "2 Members",
    theme: "Culture Quiz",
    status: "Open",
    image: "/images/whatsapp-033.jpeg"
  },
  {
    title: "Instrumental Solo",
    category: "Cultural",
    date: "2026-03-07",
    mode: "Offline",
    location: "Music Room",
    prize: "₹15,000",
    teamSize: "Individual",
    theme: "Instrumental",
    status: "Upcoming",
    image: "/images/whatsapp-034.jpeg"
  },
  {
    title: "Poster Making Competition",
    category: "Cultural",
    date: "2026-03-09",
    mode: "Offline",
    location: "Design Studio",
    prize: "₹10,000",
    teamSize: "Individual",
    theme: "Poster Design",
    status: "Open",
    image: "/images/whatsapp-035.jpeg"
  },
  {
    title: "Mono Acting",
    category: "Cultural",
    date: "2026-03-11",
    mode: "Offline",
    location: "Drama Hall",
    prize: "₹14,000",
    teamSize: "Individual",
    theme: "Mono Act",
    status: "Upcoming",
    image: "/images/whatsapp-036.jpeg"
  },
  {
    title: "Cultural Parade",
    category: "Cultural",
    date: "2026-03-13",
    mode: "Offline",
    location: "Campus Road",
    prize: "Trophies",
    teamSize: "Group",
    theme: "Traditional Parade",
    status: "Open",
    image: "/images/whatsapp-037.jpeg"
  },

  {
    title: "Singing Idol",
    category: "Cultural",
    date: "2026-03-15",
    mode: "Offline",
    location: "Main Stage",
    prize: "₹25,000",
    teamSize: "Individual",
    theme: "Singing",
    status: "Upcoming",
    image: "/images/whatsapp-038.jpeg"
  },
  {
    title: "Graffiti Art Jam",
    category: "Cultural",
    date: "2026-03-17",
    mode: "Offline",
    location: "Art Wall",
    prize: "₹12,000",
    teamSize: "2-3 Members",
    theme: "Graffiti",
    status: "Open",
    image: "/images/whatsapp-039.jpeg"
  },
  {
    title: "Short Story Writing",
    category: "Cultural",
    date: "2026-03-19",
    mode: "Online",
    location: "Submission Portal",
    prize: "₹8,000",
    teamSize: "Individual",
    theme: "Creative Writing",
    status: "Upcoming",
    image: "/images/whatsapp-040.jpeg"
  },
  {
    title: "Mime Show",
    category: "Cultural",
    date: "2026-03-21",
    mode: "Offline",
    location: "Open Theatre",
    prize: "₹10,000",
    teamSize: "3-6 Members",
    theme: "Mime",
    status: "Open",
    image: "/images/whatsapp-041.jpeg"
  },
  {
    title: "Cultural Flash Mob",
    category: "Cultural",
    date: "2026-03-23",
    mode: "Offline",
    location: "Central Plaza",
    prize: "Goodies + Trophies",
    teamSize: "Group",
    theme: "Flash Mob",
    status: "Upcoming",
    image: "/images/whatsapp-042.jpeg"
  },
  {
    title: "React Bootcamp",
    category: "Workshop",
    date: "2026-02-04",
    mode: "Online",
    location: "Zoom",
    prize: "Certificates",
    teamSize: "Individual",
    theme: "Web Development",
    status: "Open",
    image: "/images/whatsapp-043.jpeg"
  },
  {
    title: "Python for Beginners",
    category: "Workshop",
    date: "2026-02-06",
    mode: "Offline",
    location: "Computer Lab 1",
    prize: "Certificates",
    teamSize: "Individual",
    theme: "Python",
    status: "Upcoming",
    image: "/images/whatsapp-044.jpeg"
  },
  {
    title: "AI & ML Workshop",
    category: "Workshop",
    date: "2026-02-08",
    mode: "Hybrid",
    location: "Seminar Hall",
    prize: "Certificates",
    teamSize: "Individual",
    theme: "Artificial Intelligence",
    status: "Open",
    image: "/images/whatsapp-045.jpeg"
  },
  {
    title: "UI/UX Design Sprint",
    category: "Workshop",
    date: "2026-02-10",
    mode: "Offline",
    location: "Design Studio",
    prize: "Certificates",
    teamSize: "Individual",
    theme: "UI/UX",
    status: "Upcoming",
    image: "/images/whatsapp-046.jpeg"
  },
  {
    title: "Android App Development",
    category: "Workshop",
    date: "2026-02-12",
    mode: "Online",
    location: "Google Meet",
    prize: "Certificates",
    teamSize: "Individual",
    theme: "Mobile Development",
    status: "Open",
    image: "/images/whatsapp-047.jpeg"
  },

  {
    title: "Cybersecurity Basics",
    category: "Workshop",
    date: "2026-02-14",
    mode: "Offline",
    location: "IT Lab",
    prize: "Certificates",
    teamSize: "Individual",
    theme: "Cybersecurity",
    status: "Upcoming",
    image: "/images/whatsapp-048.jpeg"
  },
  {
    title: "Cloud Computing with AWS",
    category: "Workshop",
    date: "2026-02-16",
    mode: "Hybrid",
    location: "Innovation Lab",
    prize: "Certificates",
    teamSize: "Individual",
    theme: "Cloud",
    status: "Open",
    image: "/images/whatsapp-049.jpeg"
  },
  {
    title: "Data Science Hands-on",
    category: "Workshop",
    date: "2026-02-18",
    mode: "Online",
    location: "Teams",
    prize: "Certificates",
    teamSize: "Individual",
    theme: "Data Science",
    status: "Upcoming",
    image: "/images/whatsapp-050.jpeg"
  },
  {
    title: "Blockchain Fundamentals",
    category: "Workshop",
    date: "2026-02-20",
    mode: "Offline",
    location: "Conference Room",
    prize: "Certificates",
    teamSize: "Individual",
    theme: "Blockchain",
    status: "Open",
    image: "/images/whatsapp-051.jpeg"
  },
  {
    title: "DevOps Tools Training",
    category: "Workshop",
    date: "2026-02-22",
    mode: "Online",
    location: "Zoom",
    prize: "Certificates",
    teamSize: "Individual",
    theme: "DevOps",
    status: "Upcoming",
    image: "/images/whatsapp-052.jpeg"
  },

  {
    title: "IoT with Raspberry Pi",
    category: "Workshop",
    date: "2026-02-24",
    mode: "Offline",
    location: "Electronics Lab",
    prize: "Certificates",
    teamSize: "Individual",
    theme: "IoT",
    status: "Open",
    image: "/images/whatsapp-053.jpeg"
  },
  {
    title: "Game Development using Unity",
    category: "Workshop",
    date: "2026-02-26",
    mode: "Hybrid",
    location: "Game Lab",
    prize: "Certificates",
    teamSize: "Individual",
    theme: "Game Development",
    status: "Upcoming",
    image: "/images/whatsapp-054.jpeg"
  },
  {
    title: "Ethical Hacking",
    category: "Workshop",
    date: "2026-02-28",
    mode: "Offline",
    location: "Security Lab",
    prize: "Certificates",
    teamSize: "Individual",
    theme: "Hacking",
    status: "Open",
    image: "/images/whatsapp-055.jpeg"
  },
  {
    title: "Big Data Analytics",
    category: "Workshop",
    date: "2026-03-02",
    mode: "Online",
    location: "Webex",
    prize: "Certificates",
    teamSize: "Individual",
    theme: "Big Data",
    status: "Upcoming",
    image: "/images/whatsapp-056.jpeg"
  },
  {
    title: "AR/VR Development",
    category: "Workshop",
    date: "2026-03-04",
    mode: "Hybrid",
    location: "XR Lab",
    prize: "Certificates",
    teamSize: "Individual",
    theme: "AR/VR",
    status: "Open",
    image: "/images/whatsapp-057.jpeg"
  },

  {
    title: "Startup & Entrepreneurship",
    category: "Workshop",
    date: "2026-03-06",
    mode: "Offline",
    location: "Incubation Center",
    prize: "Certificates",
    teamSize: "Individual",
    theme: "Entrepreneurship",
    status: "Upcoming",
    image: "/images/whatsapp-058.jpeg"
  },
  {
    title: "Resume Building Workshop",
    category: "Workshop",
    date: "2026-03-08",
    mode: "Online",
    location: "Zoom",
    prize: "Certificates",
    teamSize: "Individual",
    theme: "Career",
    status: "Open",
    image: "/images/whatsapp-059.jpeg"
  },
  {
    title: "Interview Preparation",
    category: "Workshop",
    date: "2026-03-10",
    mode: "Offline",
    location: "Placement Cell",
    prize: "Certificates",
    teamSize: "Individual",
    theme: "Placements",
    status: "Upcoming",
    image: "/images/whatsapp-060.jpeg"
  },
  {
    title: "Public Speaking Masterclass",
    category: "Workshop",
    date: "2026-03-12",
    mode: "Offline",
    location: "Auditorium",
    prize: "Certificates",
    teamSize: "Individual",
    theme: "Communication",
    status: "Open",
    image: "/images/whatsapp-061.jpeg"
  },
  {
    title: "Time Management Workshop",
    category: "Workshop",
    date: "2026-03-14",
    mode: "Online",
    location: "Google Meet",
    prize: "Certificates",
    teamSize: "Individual",
    theme: "Productivity",
    status: "Upcoming",
    image: "/images/whatsapp-062.jpeg"
  },

  {
    title: "Digital Marketing Bootcamp",
    category: "Workshop",
    date: "2026-03-16",
    mode: "Hybrid",
    location: "Media Lab",
    prize: "Certificates",
    teamSize: "Individual",
    theme: "Marketing",
    status: "Open",
    image: "/images/whatsapp-063.jpeg"
  },
  {
    title: "Content Writing Workshop",
    category: "Workshop",
    date: "2026-03-18",
    mode: "Online",
    location: "Teams",
    prize: "Certificates",
    teamSize: "Individual",
    theme: "Writing",
    status: "Upcoming",
    image: "/images/whatsapp-064.jpeg"
  },
  {
    title: "Financial Literacy Session",
    category: "Workshop",
    date: "2026-03-20",
    mode: "Offline",
    location: "Seminar Room",
    prize: "Certificates",
    teamSize: "Individual",
    theme: "Finance",
    status: "Open",
    image: "/images/whatsapp-065.jpeg"
  },
  {
    title: "Leadership Development",
    category: "Workshop",
    date: "2026-03-22",
    mode: "Hybrid",
    location: "Training Hall",
    prize: "Certificates",
    teamSize: "Individual",
    theme: "Leadership",
    status: "Upcoming",
    image: "/images/whatsapp-066.jpeg"
  },
  {
    title: "Stress Management & Wellness",
    category: "Workshop",
    date: "2026-03-24",
    mode: "Offline",
    location: "Wellness Center",
    prize: "Certificates",
    teamSize: "Individual",
    theme: "Mental Health",
    status: "Open",
    image: "/images/whatsapp-067.jpeg"
  }

];

module.exports = { data: sampleListings };